services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=tfomat:5000
    ports:
      - "80:80"
    depends_on:
      - tfomat
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  tfomat:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    restart: always
    volumes:
      - ./app/database.db:/home/app/database.db
    ports:
      - '5000:5000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 wsgi:app
